version: "3.7"

services:
  relayer:
    env_file:
      - .env.relayer
    image: siandreev/anonymizer:relayer
    container_name: anonymizer-relayer
    command: >
      sh -c "yarn build &&
             yarn start:prod"
    ports:
      - 53000:3000
